server:
  port: 5555
# 必须设置 消费者通过服务名称调用服务
spring:
  application:
    name: zipkin
  zipkin:
    base-url: http://docker.ip:5555
  sleuth:
    sampler:
      percentage: 1.0

#logging:
#  level:
#    org:
#      springframework:
#        web:
#          servlet:
#            DispatcherServlet: debug
---
#prod
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:8888/eureka

---
#dev
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
