spring:
  profiles:
    active: dev
  application:
    name: consumer
server:
  port: 8890
feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug

---
#prod
spring:
  profiles: prod
  zipkin:
    base-url: http://172.17.0.1:5555
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:8888/eureka

---
#dev
spring:
  profiles: dev
  zipkin:
    base-url: http://172.17.0.1:5555
    enabled: false
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
