server:
  port: 8890

spring:
  application:
    name: consumer
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
feign:
  hystrix:
    enabled: true
hystrix:
  dashboard:
    proxy-stream-allow-list: "localhost"
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
