#server:
#  port: 8889
# 必须设置 消费者通过服务名称调用服务
spring:
  application:
    name: provider
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka

logging:
  level:
    org:
      springframework:
        web:
          servlet:
            DispatcherServlet: debug
