spring:
  application:
    # 必须设置 消费者通过服务名称调用服务
    name: provider
  profiles:
    active: dev
server:
  port: 8889
#logging:
#  level:
#    org:
#      springframework:
#        web:
#          servlet:
#            DispatcherServlet: debug
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

---
#prod
spring:
  profiles: prod
  zipkin:
    base-url: http://localhost:5555
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://39.107.99.242:3306/tagme?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: zyl
    password: zyl
eureka:
  client:
    service-url:
      defaultZone: http://172.17.0.1:8888/eureka

---
#dev
spring:
  profiles: dev
  zipkin:
    base-url: http://localhost:5555
    enabled: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cloud?allowPublicKeyRetrieval=true&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: root
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8888/eureka
